---
apiVersion: actions.summerwind.dev/v1alpha1
kind: RunnerDeployment
metadata:
  name: docker-images
  namespace: actions-runner-system-group
spec:
  replicas: 1
  template:
    spec:
      repository: popit-dev/docker-images